# Try valid login
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "JennyMol",
    "password": "Password"
}
###

# Try invalid login
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
    "username": "JennyMol",
    "password": "Pasword"
}
###

# Get current user
GET http://localhost:3001/api/sessions/current HTTP/1.1

###

# Log out
DELETE http://localhost:3001/api/sessions/current HTTP/1.1

###

# Get full network
GET http://localhost:3001/api/network HTTP/1.1

###

# Get ranking
GET http://localhost:3001/api/ranking HTTP/1.1

###

# Create game
POST http://localhost:3001/api/games HTTP/1.1

###

# Get game by id
GET http://localhost:3001/api/games/17 HTTP/1.1

###

# Get segments
GET http://localhost:3001/api/segments HTTP/1.1

###

# Send route
POST http://localhost:3001/api/games/17/route HTTP/1.1
content-type: application/json

{
    "route": [
        {"fromStationId": 6, "toStationId": 9},
        {"fromStationId": 9, "toStationId": 10},
        {"fromStationId": 10, "toStationId": 11}
    ]
}
###

# execute segment
POST http://localhost:3001/api/games/14/step HTTP/1.1
content-type: application/json

{
    "route": [
        {"fromStationId": 8, "toStationId": 9},
        {"fromStationId": 9, "toStationId": 10},
        {"fromStationId": 10, "toStationId": 11}
    ],
    "stepIndex": 3
}
###